### ISSUE TITLE
Navigation menu improvements

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing-client#25]
Navigation menu improvements:
- items should not wrap to multiple rows
    - should use only one row
    - items should collapse into expandable menu when screen width is narrow
- Language chooser on mobile should collapse on medium screen (hamburger menu)

**Comment by shailee-m** [comment]
@brylie 

I have changed the order a little on the topbar. Will this be okay?

1. Setting moble
![Screenshot (4)](https://user-images.githubusercontent.com/10625985/115052471-9ba20a80-9efb-11eb-9a67-fd93772af500.png)

2. Settings desktop
![Screenshot (3)](https://user-images.githubusercontent.com/10625985/115052509-a492dc00-9efb-11eb-9cf2-39fabeb95a1d.png)

3. Settings mobile expanded
![Screenshot (2)](https://user-images.githubusercontent.com/10625985/115052511-a492dc00-9efb-11eb-8a2d-6e5f224b54cb.png)

4. setting mobile collapsed
![Screenshot (1)](https://user-images.githubusercontent.com/10625985/115052513-a52b7280-9efb-11eb-892b-b0ea086420c2.png)

5. settings desktop
![Screenshot](https://user-images.githubusercontent.com/10625985/115052515-a5c40900-9efb-11eb-81c0-6624739567fc.png)
